"""initial schema

Creates all tables for the leave portal. Generated with --autogenerate, then reviewed:
- enables btree_gist first (needed by the no-overlap exclusion constraint)
- downgrade also drops the enum types, which drop_table leaves behind

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 22:50:17.512110
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Trusted extension since PG13, so the database owner can create it without superuser.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('default_annual_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('default_annual_days BETWEEN 0 AND 366', name=op.f('ck_leave_types_default_annual_days_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_types')),
    sa.UniqueConstraint('code', name=op.f('uq_leave_types_code')),
    sa.UniqueConstraint('name', name=op.f('uq_leave_types_name'))
    )
    op.create_table('public_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_public_holidays')),
    sa.UniqueConstraint('holiday_date', name=op.f('uq_public_holidays_holiday_date'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('employee', 'manager', 'admin', name='user_role'), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(role = 'employee' AND manager_id IS NOT NULL) OR (role <> 'employee' AND manager_id IS NULL)", name=op.f('ck_users_manager_only_for_employees')),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_users_email_lowercase')),
    sa.CheckConstraint('failed_login_count >= 0', name=op.f('ck_users_failed_login_count_non_negative')),
    sa.CheckConstraint('manager_id IS NULL OR manager_id <> id', name=op.f('ck_users_not_self_managed')),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_users_manager_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_manager_id'), 'users', ['manager_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('leave_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('allocated_days', sa.Integer(), nullable=False),
    sa.Column('used_days', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('allocated_days >= 0', name=op.f('ck_leave_balances_allocated_days_non_negative')),
    sa.CheckConstraint('used_days <= allocated_days', name=op.f('ck_leave_balances_used_within_allocated')),
    sa.CheckConstraint('used_days >= 0', name=op.f('ck_leave_balances_used_days_non_negative')),
    sa.CheckConstraint('year BETWEEN 2000 AND 2100', name=op.f('ck_leave_balances_year_range')),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], name=op.f('fk_leave_balances_leave_type_id_leave_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_leave_balances_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_balances')),
    sa.UniqueConstraint('user_id', 'leave_type_id', 'year', name=op.f('uq_leave_balances_user_id_leave_type_id_year'))
    )
    op.create_index(op.f('ix_leave_balances_user_id'), 'leave_balances', ['user_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='leave_status'), server_default='pending', nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decision_comment', sa.String(length=500), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('employee_id'), '='), (sa.text("daterange(start_date, end_date, '[]')"), '&&'), where=sa.text("status IN ('pending', 'approved')"), using='gist', name='ex_leave_requests_no_overlap'),
    sa.CheckConstraint("date_part('year', start_date) = date_part('year', end_date)", name=op.f('ck_leave_requests_single_calendar_year')),
    sa.CheckConstraint("status <> 'cancelled' OR (cancelled_by_id IS NOT NULL AND cancelled_at IS NOT NULL)", name=op.f('ck_leave_requests_cancellation_recorded')),
    sa.CheckConstraint("status NOT IN ('approved', 'rejected') OR (decided_by_id IS NOT NULL AND decided_at IS NOT NULL)", name=op.f('ck_leave_requests_decision_recorded')),
    sa.CheckConstraint('decided_by_id IS NULL OR decided_by_id <> employee_id', name=op.f('ck_leave_requests_not_self_decided')),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_leave_requests_end_not_before_start')),
    sa.CheckConstraint('working_days > 0', name=op.f('ck_leave_requests_working_days_positive')),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], name=op.f('fk_leave_requests_cancelled_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_leave_requests_decided_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], name=op.f('fk_leave_requests_employee_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], name=op.f('fk_leave_requests_leave_type_id_leave_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_requests'))
    )
    op.create_index('ix_leave_requests_employee_status', 'leave_requests', ['employee_id', 'status'], unique=False)
    op.create_index('ix_leave_requests_status_dates', 'leave_requests', ['status', 'start_date', 'end_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leave_requests_status_dates', table_name='leave_requests')
    op.drop_index('ix_leave_requests_employee_status', table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_leave_balances_user_id'), table_name='leave_balances')
    op.drop_table('leave_balances')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_manager_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('public_holidays')
    op.drop_table('leave_types')
    # ### end Alembic commands ###
    sa.Enum(name='leave_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='user_role').drop(op.get_bind(), checkfirst=True)
    # btree_gist is left installed: other objects in the database may rely on it.
