"""single admin account

Decision D2: exactly one admin account (the Director). A partial unique index allows at most one
row with role = 'admin'; the API also refuses to create or promote a second admin (409).

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-04 13:27:01.511464
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_users_single_admin', 'users', ['role'], unique=True, postgresql_where=sa.text("role = 'admin'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_single_admin', table_name='users', postgresql_where=sa.text("role = 'admin'"))
    # ### end Alembic commands ###
